### ISSUE TITLE
Practica de Objetos 3d con ubicación GPS

### ISSUE THREAD

**Issue by ArteezyOne** [SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-joel#2]
[Practica de Objetos 3d con ubicación GPS.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-realidad-aumentada-con-objetos-3d-joel/files/6727089/Practica.de.Objetos.3d.con.ubicacion.GPS.pdf)

**Comment by ObedG** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
